[build]
  publish = "_site"
  command = "yarn build"
  functions = "./src/_functions"

[dev]
  framework = "#custom"
  command = "yarn start"
  targetPort = 8080

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200