[build]
  publish = "_site"
  command = "yarn build"
  functions = "./src/_functions"

[dev]
  framework = "#custom"
  command = "yarn start"
  targetPort = 8080

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/recruit"
  to = "https://forms.gle/SezeFbrC3SQ1Nouz7"

[[redirects]]
  from = "/workshop"
  to = "https://ucsb.zoom.us/j/83627405229?pwd=ZlU5QzlKakVDVVVtM1lRdXZvUWtxZz09"

[[redirects]]
  from = "/mentor"
  to = "https://forms.gle/Zk4dM2cVjJfNRo7J9"